fixed NoMethodError in Ruby 1.8.x
In Ruby 1.8.x string[i] returns Fixnum object instead of String. So
unix_md5_crypt et al fail with "undefined method `length' for nn:Fixnum"
error message.